game_data = [
    {"name": "Cristiano Ronaldo", "follower_count": 387000000, "country": "Portugal", "description": "Football superstar"},
    {"name": "Katy Perry", "follower_count": 132000000, "country": "United States", "description": "Pop singer"},
    {"name": "Barack Obama", "follower_count": 140000000, "country": "United States", "description": "Former US President"},
    {"name": "BTS", "follower_count": 37000000, "country": "South Korea", "description": "K-pop group"},
    {"name": "PewDiePie", "follower_count": 110000000, "country": "Sweden", "description": "YouTube personality"},
    {"name": "Narendra Modi", "follower_count": 73000000, "country": "India", "description": "Prime Minister of India"},
    {"name": "Ellen DeGeneres", "follower_count": 79000000, "country": "United States", "description": "TV host and comedian"},
    {"name": "Rihanna", "follower_count": 101000000, "country": "Barbados", "description": "Pop singer and entrepreneur"},
    {"name": "Justin Bieber", "follower_count": 155000000, "country": "Canada", "description": "Pop singer"},
    {"name": "NASA", "follower_count": 70100000, "country": "United States", "description": "Space agency"},
    {"name": "Lionel Messi", "follower_count": 217000000, "country": "Argentina", "description": "Football superstar"},
    {"name": "Ariana Grande", "follower_count": 250000000, "country": "United States", "description": "Pop singer"},
    {"name": "Donald Trump", "follower_count": 89000000, "country": "United States", "description": "Former US President"},
    {"name": "Dwayne Johnson", "follower_count": 282000000, "country": "United States", "description": "Actor and wrestler"},
    {"name": "Netflix", "follower_count": 81000000, "country": "United States", "description": "Streaming service"},
    {"name": "Shakira", "follower_count": 170000000, "country": "Colombia", "description": "Pop singer"},
    {"name": "Bill Gates", "follower_count": 56000000, "country": "United States", "description": "Co-founder of Microsoft"},
    {"name": "The Ellen Show", "follower_count": 11000000, "country": "United States", "description": "TV show"},
    {"name": "Taylor Swift", "follower_count": 146000000, "country": "United States", "description": "Pop singer"},
    {"name": "BBC News", "follower_count": 30000000, "country": "United Kingdom", "description": "News organization"},
    {"name": "Lady Gaga", "follower_count": 89000000, "country": "United States", "description": "Pop singer"},
    {"name": "Marvel", "follower_count": 48000000, "country": "United States", "description": "Entertainment company"},
    {"name": "CNN", "follower_count": 54000000, "country": "United States", "description": "News organization"},
    {"name": "Oprah Winfrey", "follower_count": 47000000, "country": "United States", "description": "TV host and entrepreneur"},
    {"name": "Instagram", "follower_count": 430000000, "country": "United States", "description": "Social media platform"},
    {"name": "Miley Cyrus", "follower_count": 140000000, "country": "United States", "description": "Pop singer and actress"},
    {"name": "Kim Kardashian", "follower_count": 263000000, "country": "United States", "description": "TV personality and entrepreneur"},
    {"name": "Elon Musk", "follower_count": 42000000, "country": "United States", "description": "CEO of SpaceX and Tesla"},
    {"name": "Beyoncé", "follower_count": 187000000, "country": "United States", "description": "Pop singer and actress"},
    {"name": "Google", "follower_count": 26000000, "country": "United States", "description": "Technology company"},
    {"name": "Lil Wayne", "follower_count": 34000000, "country": "United States", "description": "Rapper"}
]
